### ISSUE TITLE
HAProxy debug mode enabled by default

### ISSUE THREAD

**Issue by chrisbraucker** [ZoeyVid/docker-socket-proxy#20]
Hello!
Thank you for this image, I've been using it recently and the improvements are great.
However, the container has been blasting my logging facilities with debug logs, and the reason is that, by default and without a simple option to turn it off, haproxy is started in debug mode.
(See start.sh, where `-d` is passed).

Is this intentional? I figured that the intention was to start haproxy in daemon mode (e.g. `-D`), but this breaks tini (because it forks into the background) and exits the container right after the start.

My suggestion is to simply remove the `-d` flag and optionally pass parameters from the docker `CMD` to haproxy via `"$@"`.

**Comment by Zoey2936** [comment]
Is now disabled
